### ISSUE TITLE
Unable to set API key via Pulumi config

### ISSUE THREAD

**Issue by ipince** [pulumi/pulumi-ns1#31]
Problem: I'm unable to set the NS1 API key using Pulumi config, as indicated by the docs.

I tried setting the key like this:
```
pulumi config set ns1:apiKey XXXX --secret
```

I also tried `ns1:apikey` (because it actually looks like the `vars.ts` file, and the other language implementations, all use `apikey` instead of `apiKey` as indicated by the docs). I also tried `apiKey` and `apikey`, as well as all four options without `--secret`.

In all cases, when trying to create a Record, I get the following error:
```
    error: ns1: could not find api key
```

Am I not setting the correct config?

Note: setting they key using the `NS1_APIKEY` env variable does work, but it is very much not ideal for my use case.

**Comment by stack72** [comment]
Hi @ipince 

My most sincere apologies here - it seems that we have a small typo on the docs (that I am going to fix now). The command should be:

```
pulumi config set ns1:apikey XXXX --secret
```

Notice lowercase k not uppercase like the docs produced

Sorry about this

Paul

**Comment by ipince** [comment]
Yeah, I thought it was just a typo, and I was going to submit a PR fix. But I tried using lowercase `ns1:apikey` and I still get the same error.

**Comment by stack72** [comment]
Hi @ipince 

I just check the lower casing command and it worked perfectly for me

Can you (remove any secret keys) and show me the contents of your Pulumi.<stack>.yaml file?

**Comment by ipince** [comment]
Hmm ok. I'm afk, but I can try again later and report back. Thanks!
